const tableData =  {
  tasks: [
    {
      id: "1",
      claimId: "1",
      serviceId: "1",
      typeId: "1",
      rate: "1",
      statusId: "1",
      explanation: "1",
      description: "1",
      createdAt: "1",
      updatedAt: "1",
    },
    {
      id: "1",
      claimId: "1",
      serviceId: "1",
      typeId: "1",
      rate: "1",
      statusId: "1",
      explanation: "1",
      description: "1",
      createdAt: "1",
      updatedAt: "1",
    },
    {
      id: "1",
      claimId: "1",
      serviceId: "1",
      typeId: "1",
      rate: "1",
      statusId: "1",
      explanation: "1",
      description: "1",
      createdAt: "1",
      updatedAt: "1",
    },
  ],
  meta: {
    totalItems: 9,
    itemCount: 9,
    itemsPerPage: 100,
    totalPages: 1,
    currentPage: 1,
  },
  summary: {
    name: "Итого:",
    full_price: 85177,
    full_quantity: 2607,
    full_left_cost: 7596471,
    full_sales_costs: 299704,
  },
  links: {
    first: "https://api.salero.io/products/products?limit=100",
    previous: "",
    next: "",
    last: "https://api.salero.io/products/products?page=1&limit=100",
  },
};
export default tableData
