const data = {
  managers: [
    {
      id: "1",
      name: "министертсво 1",
      phone: "3807100000",
      email: "mindpr@mail.ru",
      telegram_key: "pasha_durov",
      web_adress: "mindpr.ru",
      description: "Министертсво которое ничего не делает",
      type: "Контролирующие",
    },
    {
      id: "1",
      name: "министертсво 2",
      phone: "3807100000",
      email: "mindpr@mail.ru",
      telegram_key: "pasha_durov",
      web_adress: "mindpr.ru",
      description: "Министертсво которое ничего не делает",
      type: "Контролирующие",
    },
    {
      id: "1",
      name: "министертсво 2",
      phone: "3807100000",
      email: "mindpr@mail.ru",
      telegram_key: "pasha_durov",
      web_adress: "mindpr.ru",
      description: "Министертсво которое ничего не делает",
      type: "Контролирующие",
    },
  ],
  meta: {
    totalItems: 9,
    itemCount: 9,
    itemsPerPage: 100,
    totalPages: 1,
    currentPage: 1,
  },
  summary: {
    name: "Итого:",
    full_price: 85177,
    full_quantity: 2607,
    full_left_cost: 7596471,
    full_sales_costs: 299704,
  },
  links: {
    first: "https://api.salero.io/products/products?limit=100",
    previous: "",
    next: "",
    last: "https://api.salero.io/products/products?page=1&limit=100",
  },
};
export default data;
